# Generated by Django 4.0.1 on 2022-01-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Default', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(default='Default', upload_to='portfolio/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
